-- English localization and diplomacy for Gabriel — The Relentless Projector.

INSERT INTO Language_en_US (Tag, Text) VALUES
-- Civilization and leader identity
('TXT_KEY_CIV_GABRIEL_BOULDER_DESC', 'The Boulder Circuit'),
('TXT_KEY_CIV_GABRIEL_BOULDER_SHORT_DESC', 'The Boulder Circuit'),
('TXT_KEY_CIV_GABRIEL_BOULDER_ADJECTIVE', 'Bouldering'),
('TXT_KEY_CIV_GABRIEL_BOULDER_STRATEGY',
 '[COLOR_POSITIVE_TEXT]The Boulder Circuit[ENDCOLOR] rewards patient pressure, hill fighting, and a changing network of land routes. Keep durable land units on one enemy until [COLOR_POSITIVE_TEXT]One More Go[ENDCOLOR] reaches full strength, use Bouldering Gyms to turn hills into defensible training grounds, and redirect Caravans to unexplored destinations whenever a new Era begins.'),
('TXT_KEY_CIV_GABRIEL_BOULDER_DAWN',
 'Gabriel, Relentless Projector of the Boulder Circuit, the wall stands before you.[NEWLINE][NEWLINE]A year ago you first stepped onto the mats, uncertain how far upward the strange coloured holds might carry you. Yet session after session, failure became understanding, understanding became movement, and movement became progress.[NEWLINE][NEWLINE]Crimps tested your fingers. Slabs tested your balance. Powerful sequences tested your strength. Some problems went immediately; others followed you home unfinished, refusing to leave your thoughts until you returned.[NEWLINE][NEWLINE]Yet one wall could never satisfy you. New gyms brought unfamiliar setters, unfamiliar movements and unfamiliar challenges — and with every new problem came another opportunity to improve.[NEWLINE][NEWLINE]The world now presents the greatest project of all.[NEWLINE][NEWLINE]Will you accept failure and walk away, or will you give it One More Go?'),
('TXT_KEY_LEADER_GABRIEL_BOULDER', 'Gabriel'),
('TXT_KEY_LEADER_GABRIEL_PEDIA',
 'Gabriel is remembered as the Relentless Projector: an explorer whose steady temperament turned failed attempts into usable knowledge. Under his guidance, the Boulder Circuit became a society of travelling climbers, route setters, and careful students of difficult ground.'),

-- Unique ability and runtime notifications
('TXT_KEY_TRAIT_GABRIEL_ONE_MORE_GO', 'One More Go'),
('TXT_KEY_TRAIT_GABRIEL_ONE_MORE_GO_HELP',
 'When one of your land combat units attacks an enemy unit without destroying it, that unit begins [COLOR_POSITIVE_TEXT]Projecting[ENDCOLOR] the target. Further attacks by the same unit against the same target gain [COLOR_POSITIVE_TEXT]+5% / +10% / +15% Combat Strength[ENDCOLOR]. The bonus is lost if the unit changes targets, the target dies, or two full turns pass without another attempt. Killing the projected target on the third or a later attempt heals the attacker for [COLOR_POSITIVE_TEXT]15 HP[ENDCOLOR] and grants [COLOR_POSITIVE_TEXT]5 XP[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Fresh Sets:[ENDCOLOR] The first land Trade Route you establish to each destination city in an Era grants [ICON_RESEARCH] Science and [ICON_CULTURE] Culture equal to [COLOR_POSITIVE_TEXT]15 + 5 per Era[ENDCOLOR]. Destinations become eligible again in every new Era.'),
('TXT_KEY_GABRIEL_PROJECT_COMPLETED_NOTIFICATION',
 '[COLOR_POSITIVE_TEXT]{1_UnitName}[ENDCOLOR] sent the project: +15 HP and +5 XP.'),
('TXT_KEY_GABRIEL_FRESH_SETS_NOTIFICATION',
 'A fresh set at [COLOR_POSITIVE_TEXT]{1_CityName}[ENDCOLOR] generated +{2_Amount} [ICON_RESEARCH] Science and +{2_Amount} [ICON_CULTURE] Culture.'),
('TXT_KEY_GABRIEL_GYM_HOPPER_VISIT_NOTIFICATION',
 '[COLOR_POSITIVE_TEXT]{1_UnitName}[ENDCOLOR] visited {2_CivilizationName} territory for the first time: +2 XP.'),

-- Unit
('TXT_KEY_UNIT_GABRIEL_GYM_HOPPER', 'Gym Hopper'),
('TXT_KEY_UNIT_GABRIEL_GYM_HOPPER_HELP',
 'Replaces the Scout. Has [ICON_MOVES] 3 Movement and the [COLOR_POSITIVE_TEXT]Try Something New[ENDCOLOR] promotion: moves through Hills at double speed, gains +15% Defense on Hills, and earns +2 XP the first time it enters the territory of each other civilization or City-State. On upgrade, it loses the movement bonus but keeps +10% Defense on Hills.'),
('TXT_KEY_UNIT_GABRIEL_GYM_HOPPER_STRATEGY',
 'The Gym Hopper is a faster, hill-focused Scout. Send it across foreign borders whenever access is safe to collect its one-time exploration XP, then upgrade it into a veteran unit that retains a permanent hill-defense bonus.'),
('TXT_KEY_CIVILOPEDIA_UNITS_GABRIEL_GYM_HOPPER_TEXT',
 '[COLOR_POSITIVE_TEXT]Game Info[ENDCOLOR][NEWLINE]Unique Bouldering Scout with 3 Movement. Its Try Something New promotion grants faster movement and +15% Defense on Hills, plus +2 XP for the first visit to each foreign civilization or City-State. Its upgraded lineage retains +10% Defense on Hills.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]History[ENDCOLOR][NEWLINE]Gym hoppers carry techniques, stories, and carefully annotated beta between distant climbing communities. Their journeys turn unfamiliar landscapes into a shared circuit.'),

-- Building
('TXT_KEY_BUILDING_GABRIEL_BOULDERING_GYM', 'Bouldering Gym'),
('TXT_KEY_BUILDING_GABRIEL_BOULDERING_GYM_HELP',
 'Replaces the Barracks. Retains its training experience and additionally provides [ICON_CULTURE] +1 Culture and [ICON_HAPPINESS_1] +1 Local Happiness. Land combat units trained in this city receive [COLOR_POSITIVE_TEXT]Route Reading[ENDCOLOR] (+10% Combat Strength when attacking or defending on Hills).'),
('TXT_KEY_BUILDING_GABRIEL_BOULDERING_GYM_STRATEGY',
 'Build Bouldering Gyms early in hill cities and in the military cities that will train your main land force. Route Reading is permanent, so the building remains useful throughout the game.'),
('TXT_KEY_CIVILOPEDIA_BUILDINGS_GABRIEL_BOULDERING_GYM_TEXT',
 '[COLOR_POSITIVE_TEXT]Game Info[ENDCOLOR][NEWLINE]Unique Barracks that adds +1 Culture and +1 Local Happiness. Trained land combat units gain the permanent Route Reading promotion, giving +10% Combat Strength while attacking or defending on Hills.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]History[ENDCOLOR][NEWLINE]The Circuit''s gyms are workshops as much as training halls. Routes are reset frequently, forcing climbers to solve unfamiliar movement and teaching soldiers to read steep ground before committing to it.'),

-- Promotions
('TXT_KEY_PROMOTION_GABRIEL_TRY_SOMETHING_NEW', 'Try Something New'),
('TXT_KEY_PROMOTION_GABRIEL_TRY_SOMETHING_NEW_HELP',
 'Double movement through Hills and +15% Defense on Hills. Gains +2 XP upon the first entry into each other civilization''s or City-State''s territory. Lost on upgrade; the upgraded unit receives Hill Familiarity.'),
('TXT_KEY_PROMOTION_GABRIEL_HILL_FAMILIARITY', 'Hill Familiarity'),
('TXT_KEY_PROMOTION_GABRIEL_HILL_FAMILIARITY_HELP',
 '+10% Defense on Hills. Retained through future upgrades.'),
('TXT_KEY_PROMOTION_GABRIEL_ROUTE_READING', 'Route Reading'),
('TXT_KEY_PROMOTION_GABRIEL_ROUTE_READING_HELP',
 '+10% Combat Strength while attacking or defending on Hills. Retained through upgrades.'),
('TXT_KEY_PROMOTION_GABRIEL_DETERMINATION_1', 'Determination I'),
('TXT_KEY_PROMOTION_GABRIEL_DETERMINATION_1_HELP',
 'Projecting one specific enemy. The next attack against that target gains +5% Combat Strength. Changing targets or waiting two full turns ends the project.'),
('TXT_KEY_PROMOTION_GABRIEL_DETERMINATION_2', 'Determination II'),
('TXT_KEY_PROMOTION_GABRIEL_DETERMINATION_2_HELP',
 'Projecting one specific enemy. The next attack against that target gains +10% Combat Strength. Killing it now heals 15 HP and grants 5 XP.'),
('TXT_KEY_PROMOTION_GABRIEL_DETERMINATION_3', 'Determination III'),
('TXT_KEY_PROMOTION_GABRIEL_DETERMINATION_3_HELP',
 'Projecting one specific enemy. Further attacks against that target gain +15% Combat Strength. Killing it heals 15 HP and grants 5 XP.'),
('TXT_KEY_PROMOTION_GABRIEL_PROJECT_ATTACK_5', 'One More Go: +5%'),
('TXT_KEY_PROMOTION_GABRIEL_PROJECT_ATTACK_5_HELP',
 '+5% Combat Strength against the currently projected target.'),
('TXT_KEY_PROMOTION_GABRIEL_PROJECT_ATTACK_10', 'One More Go: +10%'),
('TXT_KEY_PROMOTION_GABRIEL_PROJECT_ATTACK_10_HELP',
 '+10% Combat Strength against the currently projected target.'),
('TXT_KEY_PROMOTION_GABRIEL_PROJECT_ATTACK_15', 'One More Go: +15%'),
('TXT_KEY_PROMOTION_GABRIEL_PROJECT_ATTACK_15_HELP',
 '+15% Combat Strength against the currently projected target.'),

-- Civilization Civilopedia
('TXT_KEY_CIV5_GABRIEL', 'The Boulder Circuit'),
('TXT_KEY_CIV5_GABRIEL_TITLE', 'The Boulder Circuit'),
('TXT_KEY_CIV5_GABRIEL_HEADING_1', 'The First Project'),
('TXT_KEY_CIV5_GABRIEL_TEXT_1',
 'The Boulder Circuit began with an unremarkable problem on an ordinary wall: a sequence that refused to yield. Gabriel returned to it after every apparent failure. He recorded which footholds slipped, which positions conserved strength, and which rests only looked comfortable. When the problem finally went, the lesson was larger than the climb. An attempt was not wasted if it made the next attempt more informed.'),
('TXT_KEY_CIV5_GABRIEL_HEADING_2', 'A Nation in Motion'),
('TXT_KEY_CIV5_GABRIEL_TEXT_2',
 'Settlements of the Circuit grew around passes, boulder fields, and the roads between them. Caravans carried food and stone, but they also brought route sketches, training methods, and news of newly discovered crags. A destination revisited in a new age could feel wholly new: equipment changed, techniques improved, and old assumptions were tested again.'),
('TXT_KEY_CIV5_GABRIEL_HEADING_3', 'The Setter''s Compact'),
('TXT_KEY_CIV5_GABRIEL_TEXT_3',
 'Every Bouldering Gym followed the Setter''s Compact. Problems were to be difficult but legible, varied but fair, and changed before habit replaced thought. The compact produced generations of soldiers and explorers who looked at rough terrain as information rather than obstruction.'),
('TXT_KEY_CIV5_GABRIEL_HEADING_4', 'The Relentless Projector'),
('TXT_KEY_CIV5_GABRIEL_TEXT_4',
 'Gabriel''s authority rested less on spectacle than on consistency. He listened, adjusted, and tried again. Rival courts sometimes misread that restraint as weakness, until they discovered that every failed assault had taught the Circuit exactly where to press next.'),

-- Leader Civilopedia
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_NAME', 'Gabriel'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL', 'Gabriel'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_SUBTITLE', 'The Relentless Projector'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_LIVED', 'The Age of the Living Circuit'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TITLES_1', 'Relentless Projector of the Boulder Circuit'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_HEADING_1', 'History'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TEXT_1',
 'Gabriel united the early climbing settlements by giving them a shared discipline: observe honestly, exchange useful knowledge, and return to unfinished work. His route journals became military manuals, his travelling partners became diplomats, and the training halls he sponsored grew into civic institutions.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_HEADING_2', 'Temperament'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_TEXT_2',
 'Gabriel prefers durable defenses, trained land forces, exploration, and constructive relations with City-States. He is methodical rather than deceptive. If war comes, he concentrates pressure on problems he has already begun to understand.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GABRIEL_FACTS_1',
 'His customary answer to a failed attempt was simple: one more go.'),

-- Cities
('TXT_KEY_CITY_NAME_GABRIEL_PROJECT', 'The Project'),
('TXT_KEY_CITY_NAME_GABRIEL_CRUX', 'Crux'),
('TXT_KEY_CITY_NAME_GABRIEL_HIGHBALL', 'Highball'),
('TXT_KEY_CITY_NAME_GABRIEL_ARETE', 'Arete'),
('TXT_KEY_CITY_NAME_GABRIEL_MANTLE', 'Mantle'),
('TXT_KEY_CITY_NAME_GABRIEL_SLAB', 'Slab'),
('TXT_KEY_CITY_NAME_GABRIEL_OVERHANG', 'Overhang'),
('TXT_KEY_CITY_NAME_GABRIEL_TRAVERSE', 'Traverse'),
('TXT_KEY_CITY_NAME_GABRIEL_CAMPUS', 'Basecamp'),
('TXT_KEY_CITY_NAME_GABRIEL_SUMMIT', 'Summit'),
('TXT_KEY_CITY_NAME_GABRIEL_CHALKSTONE', 'Chalkstone'),
('TXT_KEY_CITY_NAME_GABRIEL_BETA', 'Beta'),

-- Spies
('TXT_KEY_SPY_NAME_GABRIEL_0', 'Spotter'),
('TXT_KEY_SPY_NAME_GABRIEL_1', 'Setter'),
('TXT_KEY_SPY_NAME_GABRIEL_2', 'Belayer'),
('TXT_KEY_SPY_NAME_GABRIEL_3', 'Topo'),
('TXT_KEY_SPY_NAME_GABRIEL_4', 'Crimp'),
('TXT_KEY_SPY_NAME_GABRIEL_5', 'Dyno'),
('TXT_KEY_SPY_NAME_GABRIEL_6', 'Send'),
('TXT_KEY_SPY_NAME_GABRIEL_7', 'Chalk'),

-- Diplomacy
('TXT_KEY_LEADER_GABRIEL_FIRSTGREETING_1',
 'I am Gabriel. Every new face brings a new route through the world. Shall we compare notes?'),
('TXT_KEY_LEADER_GABRIEL_GREETING_POLITE_HELLO_1',
 'Good to see you. I have been thinking about the line ahead.'),
('TXT_KEY_LEADER_GABRIEL_GREETING_NEUTRAL_HELLO_1',
 'You are here. Tell me what problem we are solving today.'),
('TXT_KEY_LEADER_GABRIEL_GREETING_HOSTILE_HELLO_1',
 'Back again? Persistence is admirable. Direction matters too.'),
('TXT_KEY_LEADER_GABRIEL_GREETING_REPEAT_1',
 'One more go, then. What do you need?'),
('TXT_KEY_LEADER_GABRIEL_GREETING_REPEAT_TOO_MUCH_1',
 'Rest is part of training. Return when you have a clearer proposal.'),
('TXT_KEY_LEADER_GABRIEL_DOW_GENERIC_1',
 'We have studied your position long enough. Now we make the attempt.'),
('TXT_KEY_LEADER_GABRIEL_DOW_LAND_1',
 'You stand across every useful route. We will find a way through.'),
('TXT_KEY_LEADER_GABRIEL_DOW_OPPORTUNITY_1',
 'The opening is there. Refusing it would teach us nothing.'),
('TXT_KEY_LEADER_GABRIEL_DOW_REGRET_1',
 'I would rather have learned beside you. Now we will learn against you.'),
('TXT_KEY_LEADER_GABRIEL_ATTACKED_HOSTILE_1',
 'A reckless first move. We will remember every weakness it revealed.'),
('TXT_KEY_LEADER_GABRIEL_ATTACKED_EXCITED_1',
 'At last, a serious problem. Let us see who reads it better.'),
('TXT_KEY_LEADER_GABRIEL_ATTACKED_SAD_1',
 'So this is the route you chose. I had hoped for better.'),
('TXT_KEY_LEADER_GABRIEL_PEACE_OFFER_1',
 'We have both learned enough from this attempt. Let us step down safely.'),
('TXT_KEY_LEADER_GABRIEL_NO_PEACE_1',
 'Not yet. The crux remains, and we are still on the wall.'),
('TXT_KEY_LEADER_GABRIEL_DEFEATED_1',
 'The project is not erased because one climber falls. Someone will return to it.'),
('TXT_KEY_LEADER_GABRIEL_TRADE_ACCEPTABLE_1',
 'A sound exchange. Both circuits grow stronger.'),
('TXT_KEY_LEADER_GABRIEL_TRADE_GENEROUS_1',
 'That is more generous than I expected. I will remember it.'),
('TXT_KEY_LEADER_GABRIEL_TRADE_REJECT_1',
 'The sequence does not work. Change the terms and try again.'),
('TXT_KEY_LEADER_GABRIEL_TRADE_INSULTING_1',
 'That is not a proposal; it is bad beta delivered confidently.'),
('TXT_KEY_LEADER_GABRIEL_DENOUNCED_1',
 'Say what you like. The record of our actions is harder to dismiss.'),
('TXT_KEY_LEADER_GABRIEL_WARNING_1',
 'Your forces are crowding our approach. Move them, before intent becomes action.'),
('TXT_KEY_LEADER_GABRIEL_WARNING_BAD_1',
 'You ignored the line I marked. The next consequence is yours.'),
('TXT_KEY_LEADER_GABRIEL_WARNING_GOOD_1',
 'Good. Give us room, and this need go no further.'),
('TXT_KEY_LEADER_GABRIEL_REQUEST_1',
 'A small adjustment now could spare both of us a harder problem later.'),
('TXT_KEY_LEADER_GABRIEL_PLEASED_1',
 'That was well read. You have my respect.'),
('TXT_KEY_LEADER_GABRIEL_DISAPPOINTED_1',
 'You knew the safer hold and chose not to take it.'),
('TXT_KEY_LEADER_GABRIEL_OPEN_BORDERS_1',
 'Open routes teach both peoples more than closed gates. Shall we allow passage?'),
('TXT_KEY_LEADER_GABRIEL_LUXURY_TRADE_1',
 'Our people could use a change of texture. Consider this exchange.'),
('TXT_KEY_LEADER_GABRIEL_LETS_HEAR_IT_1',
 'Go on. I am listening.'),
('TXT_KEY_LEADER_GABRIEL_SO_BE_IT_1',
 'So be it. We will adapt.');

INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES
('LEADER_GABRIEL_BOULDER', 'RESPONSE_FIRST_GREETING', 'TXT_KEY_LEADER_GABRIEL_FIRSTGREETING%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_GREETING_POLITE_HELLO', 'TXT_KEY_LEADER_GABRIEL_GREETING_POLITE_HELLO%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_GREETING_NEUTRAL_HELLO', 'TXT_KEY_LEADER_GABRIEL_GREETING_NEUTRAL_HELLO%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_GREETING_HOSTILE_HELLO', 'TXT_KEY_LEADER_GABRIEL_GREETING_HOSTILE_HELLO%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_GREETING_REPEAT', 'TXT_KEY_LEADER_GABRIEL_GREETING_REPEAT%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_GREETING_REPEAT_TOO_MUCH', 'TXT_KEY_LEADER_GABRIEL_GREETING_REPEAT_TOO_MUCH%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_DOW_GENERIC', 'TXT_KEY_LEADER_GABRIEL_DOW_GENERIC%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_DOW_LAND', 'TXT_KEY_LEADER_GABRIEL_DOW_LAND%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_DOW_OPPORTUNITY', 'TXT_KEY_LEADER_GABRIEL_DOW_OPPORTUNITY%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_DOW_REGRET', 'TXT_KEY_LEADER_GABRIEL_DOW_REGRET%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_ATTACKED_HOSTILE', 'TXT_KEY_LEADER_GABRIEL_ATTACKED_HOSTILE%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_ATTACKED_EXCITED', 'TXT_KEY_LEADER_GABRIEL_ATTACKED_EXCITED%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_ATTACKED_SAD', 'TXT_KEY_LEADER_GABRIEL_ATTACKED_SAD%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_PEACE_OFFER', 'TXT_KEY_LEADER_GABRIEL_PEACE_OFFER%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_NO_PEACE', 'TXT_KEY_LEADER_GABRIEL_NO_PEACE%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_DEFEATED', 'TXT_KEY_LEADER_GABRIEL_DEFEATED%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_TRADE_ACCEPT_ACCEPTABLE', 'TXT_KEY_LEADER_GABRIEL_TRADE_ACCEPTABLE%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_TRADE_ACCEPT_GENEROUS', 'TXT_KEY_LEADER_GABRIEL_TRADE_GENEROUS%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_TRADE_REJECT_UNACCEPTABLE', 'TXT_KEY_LEADER_GABRIEL_TRADE_REJECT%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_TRADE_REJECT_INSULTING', 'TXT_KEY_LEADER_GABRIEL_TRADE_INSULTING%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 'TXT_KEY_LEADER_GABRIEL_DENOUNCED%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_AGGRESSIVE_MILITARY_WARNING', 'TXT_KEY_LEADER_GABRIEL_WARNING%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_AGGRESSIVE_MILITARY_WARNING_BAD', 'TXT_KEY_LEADER_GABRIEL_WARNING_BAD%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_AGGRESSIVE_MILITARY_WARNING_GOOD', 'TXT_KEY_LEADER_GABRIEL_WARNING_GOOD%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_REQUEST', 'TXT_KEY_LEADER_GABRIEL_REQUEST%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_PLEASED', 'TXT_KEY_LEADER_GABRIEL_PLEASED%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_DISAPPOINTED', 'TXT_KEY_LEADER_GABRIEL_DISAPPOINTED%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_OPEN_BORDERS_EXCHANGE', 'TXT_KEY_LEADER_GABRIEL_OPEN_BORDERS%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_LUXURY_TRADE', 'TXT_KEY_LEADER_GABRIEL_LUXURY_TRADE%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_LETS_HEAR_IT', 'TXT_KEY_LEADER_GABRIEL_LETS_HEAR_IT%', 1),
('LEADER_GABRIEL_BOULDER', 'RESPONSE_SO_BE_IT', 'TXT_KEY_LEADER_GABRIEL_SO_BE_IT%', 1);
